version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
